// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoc/core/core.proto

package core

import (
	context "context"
	fmt "fmt"
	math "math"

	gossip "study/GitHub/consensus/protoc/gossip"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Executetx struct {
	Tx                   string   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Executetx) Reset()         { *m = Executetx{} }
func (m *Executetx) String() string { return proto.CompactTextString(m) }
func (*Executetx) ProtoMessage()    {}
func (*Executetx) Descriptor() ([]byte, []int) {
	return fileDescriptor_5321279be68e6a2e, []int{0}
}

func (m *Executetx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Executetx.Unmarshal(m, b)
}
func (m *Executetx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Executetx.Marshal(b, m, deterministic)
}
func (m *Executetx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Executetx.Merge(m, src)
}
func (m *Executetx) XXX_Size() int {
	return xxx_messageInfo_Executetx.Size(m)
}
func (m *Executetx) XXX_DiscardUnknown() {
	xxx_messageInfo_Executetx.DiscardUnknown(m)
}

var xxx_messageInfo_Executetx proto.InternalMessageInfo

func (m *Executetx) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

func (m *Executetx) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type ExecResponse struct {
	Sign                 string   `protobuf:"bytes,1,opt,name=Sign,proto3" json:"Sign,omitempty"`
	Result               []byte   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5321279be68e6a2e, []int{1}
}

func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResponse.Unmarshal(m, b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
}
func (m *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(m, src)
}
func (m *ExecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecResponse.Size(m)
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

func (m *ExecResponse) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *ExecResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Executetx)(nil), "core.Executetx")
	proto.RegisterType((*ExecResponse)(nil), "core.ExecResponse")
}

func init() { proto.RegisterFile("protoc/core/core.proto", fileDescriptor_5321279be68e6a2e) }

var fileDescriptor_5321279be68e6a2e = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0xaf, 0xf5, 0x38, 0xb8, 0xdc, 0x9d, 0xc2, 0x1b, 0x4a, 0xa9, 0x4b, 0xe9, 0xd4, 0x29,
	0x05, 0x5d, 0x44, 0x5d, 0x3c, 0xb9, 0xc1, 0x41, 0x90, 0x2a, 0x0e, 0x6e, 0xb9, 0xf8, 0x0c, 0xc5,
	0x9a, 0x94, 0xe4, 0x15, 0xea, 0xbf, 0xe7, 0x5f, 0x26, 0x4d, 0x23, 0xde, 0x72, 0x4b, 0xf2, 0xbe,
	0x97, 0xef, 0x23, 0xef, 0x97, 0xb0, 0xa4, 0xb3, 0x86, 0x8c, 0xac, 0xa4, 0xb1, 0xe8, 0x17, 0xee,
	0x1b, 0x30, 0x1f, 0xeb, 0xec, 0x5c, 0x19, 0xa3, 0x5a, 0xac, 0x7c, 0x6f, 0xdf, 0x7f, 0x54, 0xf8,
	0xd5, 0xd1, 0xf7, 0x64, 0xc9, 0xb2, 0x10, 0x55, 0xc6, 0xb9, 0xa6, 0x0b, 0xdb, 0x74, 0x56, 0x54,
	0x6c, 0xb9, 0x1b, 0x50, 0xf6, 0x84, 0x34, 0xc0, 0x29, 0x8b, 0x69, 0x48, 0xa3, 0x3c, 0x2a, 0x97,
	0x75, 0x4c, 0x03, 0x00, 0x9b, 0xdf, 0x59, 0xe5, 0xd2, 0x38, 0x3f, 0x29, 0x97, 0xb5, 0xaf, 0x8b,
	0x6b, 0xb6, 0x1e, 0x03, 0x35, 0xba, 0xce, 0x68, 0x87, 0xa3, 0xe7, 0xb9, 0x51, 0x3a, 0xa4, 0x7c,
	0x0d, 0x09, 0x5b, 0x58, 0x74, 0x7d, 0x4b, 0x69, 0x9c, 0x47, 0xe5, 0xba, 0x0e, 0xea, 0xe2, 0x27,
	0x62, 0xab, 0x27, 0x44, 0xfb, 0x28, 0xb4, 0x50, 0x68, 0xe1, 0x96, 0xad, 0x1f, 0x74, 0x43, 0xf7,
	0x46, 0x93, 0x15, 0x92, 0x20, 0xe1, 0x13, 0x06, 0xff, 0xc3, 0xe0, 0xbb, 0x11, 0x23, 0x03, 0xee,
	0x81, 0x0f, 0xef, 0x2d, 0x66, 0x70, 0xc3, 0x20, 0x8c, 0xfe, 0x62, 0x85, 0x76, 0x42, 0x52, 0x63,
	0x34, 0x9c, 0xfd, 0x7b, 0x3d, 0xd4, 0x91, 0xf0, 0x15, 0xdb, 0xbc, 0x8a, 0xb6, 0x79, 0x17, 0x84,
	0xdb, 0xd6, 0xc8, 0x4f, 0xd8, 0xf0, 0xf0, 0x2e, 0x5e, 0x66, 0x47, 0x46, 0x29, 0x66, 0xdb, 0xcd,
	0xdb, 0xea, 0xe0, 0x2b, 0xf6, 0x0b, 0x2f, 0x2e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x00,
	0x1a, 0x55, 0xa0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PeerManagerClient is the client API for PeerManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeerManagerClient interface {
	InitContract(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ExecResponse, error)
	ExecuteTransaction(ctx context.Context, in *Executetx, opts ...grpc.CallOption) (*ExecResponse, error)
	ValidateBlock(ctx context.Context, in *gossip.Block, opts ...grpc.CallOption) (*empty.Empty, error)
}

type peerManagerClient struct {
	cc *grpc.ClientConn
}

func NewPeerManagerClient(cc *grpc.ClientConn) PeerManagerClient {
	return &peerManagerClient{cc}
}

func (c *peerManagerClient) InitContract(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, "/core.PeerManager/InitContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerManagerClient) ExecuteTransaction(ctx context.Context, in *Executetx, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, "/core.PeerManager/ExecuteTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerManagerClient) ValidateBlock(ctx context.Context, in *gossip.Block, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/core.PeerManager/ValidateBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerManagerServer is the server API for PeerManager service.
type PeerManagerServer interface {
	InitContract(context.Context, *empty.Empty) (*ExecResponse, error)
	ExecuteTransaction(context.Context, *Executetx) (*ExecResponse, error)
	ValidateBlock(context.Context, *gossip.Block) (*empty.Empty, error)
}

func RegisterPeerManagerServer(s *grpc.Server, srv PeerManagerServer) {
	s.RegisterService(&_PeerManager_serviceDesc, srv)
}

func _PeerManager_InitContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerManagerServer).InitContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.PeerManager/InitContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerManagerServer).InitContract(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerManager_ExecuteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Executetx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerManagerServer).ExecuteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.PeerManager/ExecuteTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerManagerServer).ExecuteTransaction(ctx, req.(*Executetx))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerManager_ValidateBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(gossip.Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerManagerServer).ValidateBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.PeerManager/ValidateBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerManagerServer).ValidateBlock(ctx, req.(*gossip.Block))
	}
	return interceptor(ctx, in, info, handler)
}

var _PeerManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.PeerManager",
	HandlerType: (*PeerManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitContract",
			Handler:    _PeerManager_InitContract_Handler,
		},
		{
			MethodName: "ExecuteTransaction",
			Handler:    _PeerManager_ExecuteTransaction_Handler,
		},
		{
			MethodName: "ValidateBlock",
			Handler:    _PeerManager_ValidateBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/core/core.proto",
}
