version: '3.3'
services: 
  discovery:
    build:
      context: ./
      dockerfile: ./discovery/Dockerfile
      args:
        buildno: 1
    ports: 
        - "50050:50050"

  server:
    build: 
      context: ./
      dockerfile: ./core/Dockerfile
      args: 
        buildno: 2
    ports: 
      - "50051:50051"
    # restart: always

  contract:
    build:
      context: ./
      dockerfile: ./example_cc/Dockerfile
      args:
        buildno: 3
    ports: 
      - "50053:50053"

  gossip:
    build:
      context: ./
      dockerfile: ./gossip/Dockerfile
      args:
        buildno: 4
    ports:
      - "50052:50052"

  # orderer:
  #   build:
  #     context: ./
  #     dockerfile: ./orderer/Dockerfile
  #     args:
  #       buildno: 4
  #   ports: 
  #     - "50054:50054"

  # db:
  #   image: couchdb:2.3.0
  #   ports: 5984
  #   networks: 
  #     - backend
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure