// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contractcode.proto

package protoc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InfoMsg_MsgType int32

const (
	InfoMsg_SUCESS InfoMsg_MsgType = 0
	InfoMsg_ERROR  InfoMsg_MsgType = 1
)

var InfoMsg_MsgType_name = map[int32]string{
	0: "SUCESS",
	1: "ERROR",
}

var InfoMsg_MsgType_value = map[string]int32{
	"SUCESS": 0,
	"ERROR":  1,
}

func (x InfoMsg_MsgType) String() string {
	return proto.EnumName(InfoMsg_MsgType_name, int32(x))
}

func (InfoMsg_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{0, 0}
}

type StateInfo_MsgType int32

const (
	StateInfo_SUCESS StateInfo_MsgType = 0
	StateInfo_ERROR  StateInfo_MsgType = 1
)

var StateInfo_MsgType_name = map[int32]string{
	0: "SUCESS",
	1: "ERROR",
}

var StateInfo_MsgType_value = map[string]int32{
	"SUCESS": 0,
	"ERROR":  1,
}

func (x StateInfo_MsgType) String() string {
	return proto.EnumName(StateInfo_MsgType_name, int32(x))
}

func (StateInfo_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{2, 0}
}

type TransactionResponse_QueryType int32

const (
	TransactionResponse_GETSTATE TransactionResponse_QueryType = 0
	TransactionResponse_PUTSTATE TransactionResponse_QueryType = 1
	TransactionResponse_DELSTATE TransactionResponse_QueryType = 2
)

var TransactionResponse_QueryType_name = map[int32]string{
	0: "GETSTATE",
	1: "PUTSTATE",
	2: "DELSTATE",
}

var TransactionResponse_QueryType_value = map[string]int32{
	"GETSTATE": 0,
	"PUTSTATE": 1,
	"DELSTATE": 2,
}

func (x TransactionResponse_QueryType) String() string {
	return proto.EnumName(TransactionResponse_QueryType_name, int32(x))
}

func (TransactionResponse_QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{9, 0}
}

type InfoMsg struct {
	Msg                  string          `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Type                 InfoMsg_MsgType `protobuf:"varint,2,opt,name=type,proto3,enum=protoc.InfoMsg_MsgType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InfoMsg) Reset()         { *m = InfoMsg{} }
func (m *InfoMsg) String() string { return proto.CompactTextString(m) }
func (*InfoMsg) ProtoMessage()    {}
func (*InfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{0}
}

func (m *InfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoMsg.Unmarshal(m, b)
}
func (m *InfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoMsg.Marshal(b, m, deterministic)
}
func (m *InfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoMsg.Merge(m, src)
}
func (m *InfoMsg) XXX_Size() int {
	return xxx_messageInfo_InfoMsg.Size(m)
}
func (m *InfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InfoMsg proto.InternalMessageInfo

func (m *InfoMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *InfoMsg) GetType() InfoMsg_MsgType {
	if m != nil {
		return m.Type
	}
	return InfoMsg_SUCESS
}

type TransferMessage struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FromAccId            string   `protobuf:"bytes,2,opt,name=FromAccId,proto3" json:"FromAccId,omitempty"`
	ToAccId              string   `protobuf:"bytes,3,opt,name=ToAccId,proto3" json:"ToAccId,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferMessage) Reset()         { *m = TransferMessage{} }
func (m *TransferMessage) String() string { return proto.CompactTextString(m) }
func (*TransferMessage) ProtoMessage()    {}
func (*TransferMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{1}
}

func (m *TransferMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferMessage.Unmarshal(m, b)
}
func (m *TransferMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferMessage.Marshal(b, m, deterministic)
}
func (m *TransferMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferMessage.Merge(m, src)
}
func (m *TransferMessage) XXX_Size() int {
	return xxx_messageInfo_TransferMessage.Size(m)
}
func (m *TransferMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TransferMessage proto.InternalMessageInfo

func (m *TransferMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TransferMessage) GetFromAccId() string {
	if m != nil {
		return m.FromAccId
	}
	return ""
}

func (m *TransferMessage) GetToAccId() string {
	if m != nil {
		return m.ToAccId
	}
	return ""
}

func (m *TransferMessage) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type StateInfo struct {
	Msg                  StateInfo_MsgType `protobuf:"varint,1,opt,name=Msg,proto3,enum=protoc.StateInfo_MsgType" json:"Msg,omitempty"`
	Payload              []byte            `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Sign                 string            `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StateInfo) Reset()         { *m = StateInfo{} }
func (m *StateInfo) String() string { return proto.CompactTextString(m) }
func (*StateInfo) ProtoMessage()    {}
func (*StateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{2}
}

func (m *StateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateInfo.Unmarshal(m, b)
}
func (m *StateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateInfo.Marshal(b, m, deterministic)
}
func (m *StateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateInfo.Merge(m, src)
}
func (m *StateInfo) XXX_Size() int {
	return xxx_messageInfo_StateInfo.Size(m)
}
func (m *StateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StateInfo proto.InternalMessageInfo

func (m *StateInfo) GetMsg() StateInfo_MsgType {
	if m != nil {
		return m.Msg
	}
	return StateInfo_SUCESS
}

func (m *StateInfo) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StateInfo) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type UserInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Balance              int32    `protobuf:"varint,3,opt,name=Balance,proto3" json:"Balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type GetState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetState) Reset()         { *m = GetState{} }
func (m *GetState) String() string { return proto.CompactTextString(m) }
func (*GetState) ProtoMessage()    {}
func (*GetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{4}
}

func (m *GetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetState.Unmarshal(m, b)
}
func (m *GetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetState.Marshal(b, m, deterministic)
}
func (m *GetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetState.Merge(m, src)
}
func (m *GetState) XXX_Size() int {
	return xxx_messageInfo_GetState.Size(m)
}
func (m *GetState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetState.DiscardUnknown(m)
}

var xxx_messageInfo_GetState proto.InternalMessageInfo

func (m *GetState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetState) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PutState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutState) Reset()         { *m = PutState{} }
func (m *PutState) String() string { return proto.CompactTextString(m) }
func (*PutState) ProtoMessage()    {}
func (*PutState) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{5}
}

func (m *PutState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutState.Unmarshal(m, b)
}
func (m *PutState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutState.Marshal(b, m, deterministic)
}
func (m *PutState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutState.Merge(m, src)
}
func (m *PutState) XXX_Size() int {
	return xxx_messageInfo_PutState.Size(m)
}
func (m *PutState) XXX_DiscardUnknown() {
	xxx_messageInfo_PutState.DiscardUnknown(m)
}

var xxx_messageInfo_PutState proto.InternalMessageInfo

func (m *PutState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutState) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DeleteState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteState) Reset()         { *m = DeleteState{} }
func (m *DeleteState) String() string { return proto.CompactTextString(m) }
func (*DeleteState) ProtoMessage()    {}
func (*DeleteState) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{6}
}

func (m *DeleteState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteState.Unmarshal(m, b)
}
func (m *DeleteState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteState.Marshal(b, m, deterministic)
}
func (m *DeleteState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteState.Merge(m, src)
}
func (m *DeleteState) XXX_Size() int {
	return xxx_messageInfo_DeleteState.Size(m)
}
func (m *DeleteState) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteState.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteState proto.InternalMessageInfo

func (m *DeleteState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteState) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ContractInfo struct {
	Transaction          string   `protobuf:"bytes,1,opt,name=Transaction,proto3" json:"Transaction,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractInfo) Reset()         { *m = ContractInfo{} }
func (m *ContractInfo) String() string { return proto.CompactTextString(m) }
func (*ContractInfo) ProtoMessage()    {}
func (*ContractInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{7}
}

func (m *ContractInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractInfo.Unmarshal(m, b)
}
func (m *ContractInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractInfo.Marshal(b, m, deterministic)
}
func (m *ContractInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractInfo.Merge(m, src)
}
func (m *ContractInfo) XXX_Size() int {
	return xxx_messageInfo_ContractInfo.Size(m)
}
func (m *ContractInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContractInfo proto.InternalMessageInfo

func (m *ContractInfo) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

func (m *ContractInfo) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type Response struct {
	Result               []byte   `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{8}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type TransactionResponse struct {
	Query                TransactionResponse_QueryType `protobuf:"varint,1,opt,name=Query,proto3,enum=protoc.TransactionResponse_QueryType" json:"Query,omitempty"`
	Payload              []byte                        `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{9}
}

func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetQuery() TransactionResponse_QueryType {
	if m != nil {
		return m.Query
	}
	return TransactionResponse_GETSTATE
}

func (m *TransactionResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterEnum("protoc.InfoMsg_MsgType", InfoMsg_MsgType_name, InfoMsg_MsgType_value)
	proto.RegisterEnum("protoc.StateInfo_MsgType", StateInfo_MsgType_name, StateInfo_MsgType_value)
	proto.RegisterEnum("protoc.TransactionResponse_QueryType", TransactionResponse_QueryType_name, TransactionResponse_QueryType_value)
	proto.RegisterType((*InfoMsg)(nil), "protoc.infoMsg")
	proto.RegisterType((*TransferMessage)(nil), "protoc.transferMessage")
	proto.RegisterType((*StateInfo)(nil), "protoc.stateInfo")
	proto.RegisterType((*UserInfo)(nil), "protoc.userInfo")
	proto.RegisterType((*GetState)(nil), "protoc.getState")
	proto.RegisterType((*PutState)(nil), "protoc.putState")
	proto.RegisterType((*DeleteState)(nil), "protoc.deleteState")
	proto.RegisterType((*ContractInfo)(nil), "protoc.contractInfo")
	proto.RegisterType((*Response)(nil), "protoc.response")
	proto.RegisterType((*TransactionResponse)(nil), "protoc.transactionResponse")
}

func init() { proto.RegisterFile("contractcode.proto", fileDescriptor_da7a8b338724b80b) }

var fileDescriptor_da7a8b338724b80b = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0x97, 0x7e, 0x26, 0x67, 0xd5, 0xa8, 0xcc, 0x34, 0x42, 0xc7, 0x45, 0x64, 0x09, 0xa9,
	0xd2, 0xa4, 0x0c, 0x15, 0x81, 0x84, 0xb8, 0x40, 0x65, 0x0b, 0x53, 0x35, 0x0a, 0x23, 0x49, 0x27,
	0x6e, 0xb3, 0xf4, 0x34, 0x2a, 0xa4, 0x71, 0x14, 0x3b, 0x48, 0x79, 0x03, 0x1e, 0x80, 0x37, 0xe0,
	0x45, 0x91, 0x1d, 0xa7, 0xdd, 0x05, 0xe5, 0xe3, 0xaa, 0xfe, 0xd9, 0xff, 0x73, 0x7c, 0xfe, 0x27,
	0xc7, 0x05, 0x12, 0xb3, 0x4c, 0x14, 0x51, 0x2c, 0x62, 0xb6, 0x44, 0x37, 0x2f, 0x98, 0x60, 0xa4,
	0xa7, 0x7e, 0xe2, 0xd1, 0x69, 0xc2, 0x58, 0x92, 0xe2, 0xb9, 0xc2, 0xbb, 0x72, 0x75, 0x8e, 0x9b,
	0x5c, 0x54, 0xb5, 0x88, 0x7e, 0x81, 0xfe, 0x3a, 0x5b, 0xb1, 0x39, 0x4f, 0xc8, 0x10, 0xda, 0x73,
	0x9e, 0xd8, 0x86, 0x63, 0x8c, 0x2d, 0x5f, 0x2e, 0xc9, 0x19, 0x74, 0x44, 0x95, 0xa3, 0xdd, 0x72,
	0x8c, 0xf1, 0xd1, 0xe4, 0x51, 0x1d, 0x12, 0xbb, 0x3a, 0xc0, 0x9d, 0xf3, 0x24, 0xac, 0x72, 0xf4,
	0x95, 0x88, 0x3a, 0xd0, 0xd7, 0x1b, 0x04, 0xa0, 0x17, 0x2c, 0x2e, 0xbc, 0x20, 0x18, 0x1e, 0x10,
	0x0b, 0xba, 0x9e, 0xef, 0x7f, 0xf4, 0x87, 0x06, 0xad, 0xe0, 0x81, 0x28, 0xa2, 0x8c, 0xaf, 0xb0,
	0x98, 0x23, 0xe7, 0x51, 0x82, 0xe4, 0x04, 0x7a, 0x0b, 0x8e, 0xc5, 0x6c, 0xa9, 0xaf, 0xd5, 0x44,
	0x9e, 0x80, 0xf5, 0xae, 0x60, 0x9b, 0x69, 0x1c, 0xcf, 0x96, 0xea, 0x7a, 0xcb, 0xdf, 0x6d, 0x10,
	0x1b, 0xfa, 0x21, 0xab, 0xcf, 0xda, 0xea, 0xac, 0x41, 0x99, 0x6f, 0xba, 0x61, 0x65, 0x26, 0xec,
	0x8e, 0x63, 0x8c, 0xbb, 0xbe, 0x26, 0xfa, 0xdd, 0x00, 0x8b, 0x8b, 0x48, 0xe0, 0x2c, 0x5b, 0x31,
	0x72, 0xb6, 0x73, 0x7a, 0x34, 0x79, 0xdc, 0xd8, 0xda, 0x9e, 0x6f, 0x8d, 0xa9, 0x26, 0xd8, 0xd0,
	0xbf, 0x89, 0xaa, 0x94, 0x45, 0x75, 0x21, 0x03, 0xbf, 0x41, 0x42, 0xa0, 0x13, 0xac, 0x93, 0x4c,
	0xd7, 0xa0, 0xd6, 0xff, 0xd0, 0x85, 0xcf, 0x60, 0x96, 0xd2, 0xa4, 0x2c, 0x64, 0x9f, 0xfd, 0x11,
	0x98, 0x72, 0xf5, 0x21, 0xda, 0xa0, 0x76, 0xbf, 0x65, 0x59, 0xcf, 0xdb, 0x28, 0x8d, 0xb2, 0x18,
	0xd5, 0xc5, 0x5d, 0xbf, 0x41, 0xfa, 0x12, 0xcc, 0x04, 0x45, 0x20, 0x6d, 0xc8, 0x8f, 0x79, 0x8d,
	0x55, 0xf3, 0x31, 0xaf, 0xb1, 0x92, 0x71, 0xb7, 0x58, 0xf0, 0x35, 0xcb, 0x74, 0xca, 0x06, 0xe9,
	0x04, 0xcc, 0xbc, 0xdc, 0x1b, 0x77, 0x0c, 0xdd, 0xdb, 0x28, 0x2d, 0x51, 0xbb, 0xaf, 0x81, 0xbe,
	0x82, 0xc3, 0x25, 0xa6, 0x28, 0xf0, 0xff, 0xaf, 0xbb, 0x84, 0x41, 0x33, 0xad, 0xaa, 0x09, 0x0e,
	0x1c, 0x86, 0x72, 0x2c, 0xa2, 0x58, 0x48, 0x75, 0x9d, 0xe3, 0xfe, 0x96, 0x6c, 0xf4, 0xb4, 0x48,
	0xb8, 0xdd, 0x72, 0xda, 0xb2, 0xd1, 0x72, 0x4d, 0x29, 0x98, 0x05, 0xf2, 0x9c, 0x65, 0x5c, 0x4d,
	0x91, 0x8f, 0xbc, 0x4c, 0x85, 0xae, 0x51, 0x13, 0xfd, 0x69, 0xc0, 0x43, 0xb1, 0xcb, 0xe3, 0x37,
	0xfa, 0xd7, 0xd0, 0xfd, 0x54, 0x62, 0x51, 0xe9, 0x09, 0x78, 0xda, 0x4c, 0xc0, 0x6f, 0xb4, 0xae,
	0x12, 0xaa, 0x69, 0xa8, 0x63, 0xf6, 0xcf, 0x03, 0x7d, 0x01, 0xd6, 0x56, 0x4d, 0x06, 0x60, 0x5e,
	0x79, 0x61, 0x10, 0x4e, 0x43, 0x6f, 0x78, 0x20, 0xe9, 0x66, 0xa1, 0xc9, 0x90, 0x74, 0xe9, 0xbd,
	0xaf, 0xa9, 0x35, 0xf9, 0x61, 0x80, 0x79, 0xa1, 0x1b, 0x42, 0xae, 0x60, 0x30, 0xcb, 0xd6, 0x62,
	0xcb, 0x27, 0x6e, 0xfd, 0x7a, 0xdd, 0xe6, 0xf5, 0xba, 0x9e, 0x7c, 0xbd, 0xa3, 0xd3, 0x3f, 0xd4,
	0x4c, 0x0f, 0x9e, 0x19, 0xe4, 0x0d, 0xf4, 0x66, 0xd9, 0x37, 0xf6, 0x15, 0xc9, 0x71, 0x23, 0xbd,
	0xdf, 0xf5, 0xbf, 0x26, 0xb8, 0xab, 0xff, 0x3e, 0x9e, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x72,
	0x9b, 0x1f, 0xbf, 0x5b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContractClient is the client API for Contract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContractClient interface {
	InitContract(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Contract_InitContractClient, error)
	Invoke(ctx context.Context, in *ContractInfo, opts ...grpc.CallOption) (Contract_InvokeClient, error)
}

type contractClient struct {
	cc *grpc.ClientConn
}

func NewContractClient(cc *grpc.ClientConn) ContractClient {
	return &contractClient{cc}
}

func (c *contractClient) InitContract(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Contract_InitContractClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Contract_serviceDesc.Streams[0], "/protoc.Contract/InitContract", opts...)
	if err != nil {
		return nil, err
	}
	x := &contractInitContractClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Contract_InitContractClient interface {
	Recv() (*TransactionResponse, error)
	grpc.ClientStream
}

type contractInitContractClient struct {
	grpc.ClientStream
}

func (x *contractInitContractClient) Recv() (*TransactionResponse, error) {
	m := new(TransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *contractClient) Invoke(ctx context.Context, in *ContractInfo, opts ...grpc.CallOption) (Contract_InvokeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Contract_serviceDesc.Streams[1], "/protoc.Contract/Invoke", opts...)
	if err != nil {
		return nil, err
	}
	x := &contractInvokeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Contract_InvokeClient interface {
	Recv() (*TransactionResponse, error)
	grpc.ClientStream
}

type contractInvokeClient struct {
	grpc.ClientStream
}

func (x *contractInvokeClient) Recv() (*TransactionResponse, error) {
	m := new(TransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContractServer is the server API for Contract service.
type ContractServer interface {
	InitContract(*empty.Empty, Contract_InitContractServer) error
	Invoke(*ContractInfo, Contract_InvokeServer) error
}

func RegisterContractServer(s *grpc.Server, srv ContractServer) {
	s.RegisterService(&_Contract_serviceDesc, srv)
}

func _Contract_InitContract_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContractServer).InitContract(m, &contractInitContractServer{stream})
}

type Contract_InitContractServer interface {
	Send(*TransactionResponse) error
	grpc.ServerStream
}

type contractInitContractServer struct {
	grpc.ServerStream
}

func (x *contractInitContractServer) Send(m *TransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Contract_Invoke_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContractInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContractServer).Invoke(m, &contractInvokeServer{stream})
}

type Contract_InvokeServer interface {
	Send(*TransactionResponse) error
	grpc.ServerStream
}

type contractInvokeServer struct {
	grpc.ServerStream
}

func (x *contractInvokeServer) Send(m *TransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Contract_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.Contract",
	HandlerType: (*ContractServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InitContract",
			Handler:       _Contract_InitContract_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Invoke",
			Handler:       _Contract_Invoke_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "contractcode.proto",
}
