// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contractcode.proto

package protoc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InfoMsg_MsgType int32

const (
	InfoMsg_SUCESS InfoMsg_MsgType = 0
	InfoMsg_ERROR  InfoMsg_MsgType = 1
)

var InfoMsg_MsgType_name = map[int32]string{
	0: "SUCESS",
	1: "ERROR",
}

var InfoMsg_MsgType_value = map[string]int32{
	"SUCESS": 0,
	"ERROR":  1,
}

func (x InfoMsg_MsgType) String() string {
	return proto.EnumName(InfoMsg_MsgType_name, int32(x))
}

func (InfoMsg_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{0, 0}
}

type StateInfo_MsgType int32

const (
	StateInfo_SUCESS StateInfo_MsgType = 0
	StateInfo_ERROR  StateInfo_MsgType = 1
)

var StateInfo_MsgType_name = map[int32]string{
	0: "SUCESS",
	1: "ERROR",
}

var StateInfo_MsgType_value = map[string]int32{
	"SUCESS": 0,
	"ERROR":  1,
}

func (x StateInfo_MsgType) String() string {
	return proto.EnumName(StateInfo_MsgType_name, int32(x))
}

func (StateInfo_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{2, 0}
}

type InfoMsg struct {
	Msg                  string          `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Type                 InfoMsg_MsgType `protobuf:"varint,2,opt,name=type,proto3,enum=protoc.InfoMsg_MsgType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InfoMsg) Reset()         { *m = InfoMsg{} }
func (m *InfoMsg) String() string { return proto.CompactTextString(m) }
func (*InfoMsg) ProtoMessage()    {}
func (*InfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{0}
}

func (m *InfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoMsg.Unmarshal(m, b)
}
func (m *InfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoMsg.Marshal(b, m, deterministic)
}
func (m *InfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoMsg.Merge(m, src)
}
func (m *InfoMsg) XXX_Size() int {
	return xxx_messageInfo_InfoMsg.Size(m)
}
func (m *InfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InfoMsg proto.InternalMessageInfo

func (m *InfoMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *InfoMsg) GetType() InfoMsg_MsgType {
	if m != nil {
		return m.Type
	}
	return InfoMsg_SUCESS
}

type TransferMessage struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FromAccId            string   `protobuf:"bytes,2,opt,name=FromAccId,proto3" json:"FromAccId,omitempty"`
	ToAccId              string   `protobuf:"bytes,3,opt,name=ToAccId,proto3" json:"ToAccId,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferMessage) Reset()         { *m = TransferMessage{} }
func (m *TransferMessage) String() string { return proto.CompactTextString(m) }
func (*TransferMessage) ProtoMessage()    {}
func (*TransferMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{1}
}

func (m *TransferMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferMessage.Unmarshal(m, b)
}
func (m *TransferMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferMessage.Marshal(b, m, deterministic)
}
func (m *TransferMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferMessage.Merge(m, src)
}
func (m *TransferMessage) XXX_Size() int {
	return xxx_messageInfo_TransferMessage.Size(m)
}
func (m *TransferMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TransferMessage proto.InternalMessageInfo

func (m *TransferMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TransferMessage) GetFromAccId() string {
	if m != nil {
		return m.FromAccId
	}
	return ""
}

func (m *TransferMessage) GetToAccId() string {
	if m != nil {
		return m.ToAccId
	}
	return ""
}

func (m *TransferMessage) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type StateInfo struct {
	Msg                  StateInfo_MsgType `protobuf:"varint,1,opt,name=Msg,proto3,enum=protoc.StateInfo_MsgType" json:"Msg,omitempty"`
	Payload              []byte            `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Sign                 string            `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StateInfo) Reset()         { *m = StateInfo{} }
func (m *StateInfo) String() string { return proto.CompactTextString(m) }
func (*StateInfo) ProtoMessage()    {}
func (*StateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{2}
}

func (m *StateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateInfo.Unmarshal(m, b)
}
func (m *StateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateInfo.Marshal(b, m, deterministic)
}
func (m *StateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateInfo.Merge(m, src)
}
func (m *StateInfo) XXX_Size() int {
	return xxx_messageInfo_StateInfo.Size(m)
}
func (m *StateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StateInfo proto.InternalMessageInfo

func (m *StateInfo) GetMsg() StateInfo_MsgType {
	if m != nil {
		return m.Msg
	}
	return StateInfo_SUCESS
}

func (m *StateInfo) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StateInfo) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type UserInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Balance              int32    `protobuf:"varint,3,opt,name=Balance,proto3" json:"Balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type GetState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetState) Reset()         { *m = GetState{} }
func (m *GetState) String() string { return proto.CompactTextString(m) }
func (*GetState) ProtoMessage()    {}
func (*GetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{4}
}

func (m *GetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetState.Unmarshal(m, b)
}
func (m *GetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetState.Marshal(b, m, deterministic)
}
func (m *GetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetState.Merge(m, src)
}
func (m *GetState) XXX_Size() int {
	return xxx_messageInfo_GetState.Size(m)
}
func (m *GetState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetState.DiscardUnknown(m)
}

var xxx_messageInfo_GetState proto.InternalMessageInfo

func (m *GetState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type PutState struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutState) Reset()         { *m = PutState{} }
func (m *PutState) String() string { return proto.CompactTextString(m) }
func (*PutState) ProtoMessage()    {}
func (*PutState) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{5}
}

func (m *PutState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutState.Unmarshal(m, b)
}
func (m *PutState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutState.Marshal(b, m, deterministic)
}
func (m *PutState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutState.Merge(m, src)
}
func (m *PutState) XXX_Size() int {
	return xxx_messageInfo_PutState.Size(m)
}
func (m *PutState) XXX_DiscardUnknown() {
	xxx_messageInfo_PutState.DiscardUnknown(m)
}

var xxx_messageInfo_PutState proto.InternalMessageInfo

func (m *PutState) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutState) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ContractInfo struct {
	Transaction          string   `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Args                 []byte   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractInfo) Reset()         { *m = ContractInfo{} }
func (m *ContractInfo) String() string { return proto.CompactTextString(m) }
func (*ContractInfo) ProtoMessage()    {}
func (*ContractInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{6}
}

func (m *ContractInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractInfo.Unmarshal(m, b)
}
func (m *ContractInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractInfo.Marshal(b, m, deterministic)
}
func (m *ContractInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractInfo.Merge(m, src)
}
func (m *ContractInfo) XXX_Size() int {
	return xxx_messageInfo_ContractInfo.Size(m)
}
func (m *ContractInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContractInfo proto.InternalMessageInfo

func (m *ContractInfo) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

func (m *ContractInfo) GetArgs() []byte {
	if m != nil {
		return m.Args
	}
	return nil
}

type Response struct {
	Result               []byte   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_da7a8b338724b80b, []int{7}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterEnum("protoc.InfoMsg_MsgType", InfoMsg_MsgType_name, InfoMsg_MsgType_value)
	proto.RegisterEnum("protoc.StateInfo_MsgType", StateInfo_MsgType_name, StateInfo_MsgType_value)
	proto.RegisterType((*InfoMsg)(nil), "protoc.infoMsg")
	proto.RegisterType((*TransferMessage)(nil), "protoc.transferMessage")
	proto.RegisterType((*StateInfo)(nil), "protoc.stateInfo")
	proto.RegisterType((*UserInfo)(nil), "protoc.userInfo")
	proto.RegisterType((*GetState)(nil), "protoc.getState")
	proto.RegisterType((*PutState)(nil), "protoc.putState")
	proto.RegisterType((*ContractInfo)(nil), "protoc.contractInfo")
	proto.RegisterType((*Response)(nil), "protoc.Response")
}

func init() { proto.RegisterFile("contractcode.proto", fileDescriptor_da7a8b338724b80b) }

var fileDescriptor_da7a8b338724b80b = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6b, 0xdb, 0x4c,
	0x10, 0xb6, 0xde, 0xf8, 0x43, 0x9a, 0xd7, 0x24, 0x66, 0x09, 0xa9, 0xea, 0xe6, 0x20, 0xf6, 0x64,
	0x08, 0x28, 0xa0, 0x9e, 0x7a, 0x4c, 0x53, 0x17, 0x74, 0x70, 0x5b, 0x56, 0x09, 0xf4, 0xba, 0x91,
	0xc7, 0xc2, 0xb5, 0xbc, 0x2b, 0xb4, 0xab, 0x80, 0xfe, 0x41, 0x7f, 0x76, 0xd9, 0xd5, 0xae, 0x13,
	0x0a, 0x81, 0x9e, 0x34, 0xcf, 0x7c, 0xec, 0x3c, 0xcf, 0xcc, 0x08, 0x48, 0x29, 0x85, 0x6e, 0x79,
	0xa9, 0x4b, 0xb9, 0xc5, 0xb4, 0x69, 0xa5, 0x96, 0x64, 0x6a, 0x3f, 0xe5, 0xf2, 0x43, 0x25, 0x65,
	0x55, 0xe3, 0xad, 0x85, 0x4f, 0xdd, 0xee, 0x16, 0x8f, 0x8d, 0xee, 0x87, 0x24, 0xfa, 0x0b, 0x66,
	0x7b, 0xb1, 0x93, 0x1b, 0x55, 0x91, 0x05, 0x9c, 0x6d, 0x54, 0x15, 0x07, 0x49, 0xb0, 0x8a, 0x98,
	0x31, 0xc9, 0x0d, 0x8c, 0x75, 0xdf, 0x60, 0xfc, 0x5f, 0x12, 0xac, 0xce, 0xb3, 0x77, 0x43, 0x49,
	0x99, 0xba, 0x82, 0x74, 0xa3, 0xaa, 0x87, 0xbe, 0x41, 0x66, 0x93, 0x68, 0x02, 0x33, 0xe7, 0x20,
	0x00, 0xd3, 0xe2, 0xf1, 0x7e, 0x5d, 0x14, 0x8b, 0x11, 0x89, 0x60, 0xb2, 0x66, 0xec, 0x3b, 0x5b,
	0x04, 0xb4, 0x87, 0x0b, 0xdd, 0x72, 0xa1, 0x76, 0xd8, 0x6e, 0x50, 0x29, 0x5e, 0x21, 0xb9, 0x82,
	0xe9, 0xa3, 0xc2, 0x36, 0xdf, 0xba, 0xb6, 0x0e, 0x91, 0x6b, 0x88, 0xbe, 0xb6, 0xf2, 0x78, 0x57,
	0x96, 0xf9, 0xd6, 0xb6, 0x8f, 0xd8, 0x8b, 0x83, 0xc4, 0x30, 0x7b, 0x90, 0x43, 0xec, 0xcc, 0xc6,
	0x3c, 0x34, 0xef, 0xdd, 0x1d, 0x65, 0x27, 0x74, 0x3c, 0x4e, 0x82, 0xd5, 0x84, 0x39, 0x44, 0x7f,
	0x07, 0x10, 0x29, 0xcd, 0x35, 0xe6, 0x62, 0x27, 0xc9, 0xcd, 0x8b, 0xd2, 0xf3, 0xec, 0xbd, 0x97,
	0x75, 0x8a, 0x9f, 0x84, 0xd9, 0x21, 0xc4, 0x30, 0xfb, 0xc1, 0xfb, 0x5a, 0xf2, 0x81, 0xc8, 0x9c,
	0x79, 0x48, 0x08, 0x8c, 0x8b, 0x7d, 0x25, 0x1c, 0x07, 0x6b, 0xff, 0xc3, 0x14, 0x7e, 0x42, 0xd8,
	0x19, 0x91, 0x86, 0xc8, 0x5b, 0xf2, 0x97, 0x10, 0x1a, 0xeb, 0x1b, 0x3f, 0xa2, 0x53, 0x7f, 0xc2,
	0x86, 0xcf, 0x67, 0x5e, 0x73, 0x51, 0xa2, 0x6d, 0x3c, 0x61, 0x1e, 0xd2, 0x6b, 0x08, 0x2b, 0xd4,
	0x85, 0x91, 0x61, 0x96, 0x79, 0xc0, 0xde, 0x2f, 0xf3, 0x80, 0x3d, 0xcd, 0x20, 0x6c, 0xba, 0xb7,
	0xa2, 0xe4, 0x12, 0x26, 0xcf, 0xbc, 0xee, 0xd0, 0x69, 0x1c, 0x00, 0xfd, 0x02, 0x73, 0x7f, 0x58,
	0x96, 0x6f, 0x02, 0xff, 0xdb, 0x0d, 0xf2, 0x52, 0xef, 0xa5, 0x70, 0xf5, 0xaf, 0x5d, 0x66, 0x26,
	0xbc, 0xad, 0x94, 0x7b, 0xc6, 0xda, 0x94, 0x42, 0xc8, 0x50, 0x35, 0x52, 0x28, 0xbb, 0xf0, 0x16,
	0x55, 0x57, 0x6b, 0x97, 0xe1, 0x50, 0xd6, 0x43, 0x78, 0xef, 0x3a, 0x91, 0x4f, 0x30, 0xcf, 0xc5,
	0x5e, 0x9f, 0xf0, 0x55, 0x3a, 0x5c, 0x70, 0xea, 0x2f, 0x38, 0x5d, 0x9b, 0x0b, 0x5e, 0x5e, 0xfc,
	0x75, 0x90, 0x74, 0x44, 0x32, 0x98, 0xe6, 0xe2, 0x59, 0x1e, 0x90, 0x5c, 0xfa, 0xe0, 0x6b, 0x01,
	0xcb, 0x85, 0xf7, 0x7a, 0x42, 0x74, 0xf4, 0x34, 0xfc, 0x27, 0x1f, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x60, 0xff, 0x3d, 0x9b, 0x44, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContractClient is the client API for Contract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContractClient interface {
	InitContract(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InfoMsg, error)
	Invoke(ctx context.Context, in *ContractInfo, opts ...grpc.CallOption) (*Response, error)
}

type contractClient struct {
	cc *grpc.ClientConn
}

func NewContractClient(cc *grpc.ClientConn) ContractClient {
	return &contractClient{cc}
}

func (c *contractClient) InitContract(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InfoMsg, error) {
	out := new(InfoMsg)
	err := c.cc.Invoke(ctx, "/protoc.Contract/InitContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractClient) Invoke(ctx context.Context, in *ContractInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protoc.Contract/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractServer is the server API for Contract service.
type ContractServer interface {
	InitContract(context.Context, *empty.Empty) (*InfoMsg, error)
	Invoke(context.Context, *ContractInfo) (*Response, error)
}

func RegisterContractServer(s *grpc.Server, srv ContractServer) {
	s.RegisterService(&_Contract_serviceDesc, srv)
}

func _Contract_InitContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).InitContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.Contract/InitContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).InitContract(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contract_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.Contract/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).Invoke(ctx, req.(*ContractInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contract_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.Contract",
	HandlerType: (*ContractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitContract",
			Handler:    _Contract_InitContract_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _Contract_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contractcode.proto",
}
