// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package registry

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// we define what a registration needs to have
// all optional and self explanatory
type Registration struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ipv4                 string   `protobuf:"bytes,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Registration) Reset()         { *m = Registration{} }
func (m *Registration) String() string { return proto.CompactTextString(m) }
func (*Registration) ProtoMessage()    {}
func (*Registration) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{0}
}

func (m *Registration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Registration.Unmarshal(m, b)
}
func (m *Registration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Registration.Marshal(b, m, deterministic)
}
func (m *Registration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Registration.Merge(m, src)
}
func (m *Registration) XXX_Size() int {
	return xxx_messageInfo_Registration.Size(m)
}
func (m *Registration) XXX_DiscardUnknown() {
	xxx_messageInfo_Registration.DiscardUnknown(m)
}

var xxx_messageInfo_Registration proto.InternalMessageInfo

func (m *Registration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Registration) GetIpv4() string {
	if m != nil {
		return m.Ipv4
	}
	return ""
}

func (m *Registration) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

// a list/array of registrations
type RegistrationList struct {
	Registrations        []*Registration `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RegistrationList) Reset()         { *m = RegistrationList{} }
func (m *RegistrationList) String() string { return proto.CompactTextString(m) }
func (*RegistrationList) ProtoMessage()    {}
func (*RegistrationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{1}
}

func (m *RegistrationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationList.Unmarshal(m, b)
}
func (m *RegistrationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationList.Marshal(b, m, deterministic)
}
func (m *RegistrationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationList.Merge(m, src)
}
func (m *RegistrationList) XXX_Size() int {
	return xxx_messageInfo_RegistrationList.Size(m)
}
func (m *RegistrationList) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationList.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationList proto.InternalMessageInfo

func (m *RegistrationList) GetRegistrations() []*Registration {
	if m != nil {
		return m.Registrations
	}
	return nil
}

// simple response when you sign up
type RegisterResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Registration)(nil), "registry.Registration")
	proto.RegisterType((*RegistrationList)(nil), "registry.RegistrationList")
	proto.RegisterType((*RegisterResponse)(nil), "registry.RegisterResponse")
}

func init() { proto.RegisterFile("discovery.proto", fileDescriptor_1e7ff60feb39c8d0) }

var fileDescriptor_1e7ff60feb39c8d0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0x2b, 0xba, 0x8e, 0x8a, 0x12, 0x64, 0x09, 0xf5, 0xb2, 0xf4, 0xb4, 0x07, 0xc9,
	0xc2, 0xea, 0x51, 0xc4, 0x8b, 0x97, 0x65, 0x0f, 0x52, 0xf1, 0x07, 0x74, 0xeb, 0x6c, 0x0d, 0xd8,
	0x4e, 0x98, 0xc4, 0x42, 0xff, 0xa9, 0x3f, 0x47, 0xd2, 0x34, 0x58, 0x15, 0x4f, 0xde, 0x5e, 0x3e,
	0x5e, 0xde, 0x0c, 0xf3, 0xe0, 0xec, 0x45, 0xdb, 0x92, 0x5a, 0xe4, 0x4e, 0x19, 0x26, 0x47, 0x62,
	0xca, 0x58, 0x69, 0xeb, 0xb8, 0x4b, 0x2f, 0x2b, 0xa2, 0xea, 0x0d, 0x97, 0x3d, 0xdf, 0xbe, 0xef,
	0x96, 0x58, 0x1b, 0x37, 0xd8, 0xb2, 0x35, 0x9c, 0xe4, 0xc1, 0x58, 0x38, 0x4d, 0x8d, 0x10, 0xb0,
	0xdf, 0x14, 0x35, 0xca, 0x64, 0x9e, 0x2c, 0x8e, 0xf2, 0x5e, 0x7b, 0xa6, 0x4d, 0x7b, 0x23, 0xf7,
	0x02, 0xf3, 0xda, 0x33, 0x43, 0xec, 0xe4, 0x24, 0x30, 0xaf, 0xb3, 0x47, 0x38, 0x1f, 0x67, 0x6d,
	0xb4, 0x75, 0xe2, 0x16, 0x4e, 0x79, 0xc4, 0xac, 0x4c, 0xe6, 0x93, 0xc5, 0xf1, 0x6a, 0xa6, 0xe2,
	0x7a, 0x6a, 0xfc, 0x25, 0xff, 0x6e, 0xce, 0xae, 0x62, 0x22, 0x72, 0x8e, 0xd6, 0x50, 0x63, 0x51,
	0x48, 0x38, 0xac, 0xd1, 0xda, 0xa2, 0x8a, 0x4b, 0xc6, 0xe7, 0xea, 0x23, 0x81, 0xe9, 0x90, 0xd6,
	0x89, 0xbb, 0xa8, 0x91, 0xc5, 0x1f, 0xd3, 0xd2, 0xf4, 0x27, 0x1f, 0x8d, 0xb9, 0x07, 0x78, 0x6e,
	0xf8, 0x3f, 0x09, 0x6b, 0xb8, 0xd8, 0xa1, 0x2b, 0x5f, 0x9f, 0x90, 0x5b, 0x5d, 0xe2, 0x86, 0xca,
	0x70, 0xe2, 0x99, 0x0a, 0x85, 0xa8, 0x58, 0x88, 0x7a, 0xf0, 0x85, 0xfc, 0xce, 0xfa, 0x3a, 0xe3,
	0xf6, 0xa0, 0xf7, 0x5e, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xde, 0x6a, 0x46, 0x40, 0xe7, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	Register(ctx context.Context, in *Registration, opts ...grpc.CallOption) (*RegisterResponse, error)
	Unregister(ctx context.Context, in *Registration, opts ...grpc.CallOption) (*RegisterResponse, error)
	FetchServiceLocation(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RegistrationList, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) Register(ctx context.Context, in *Registration, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) Unregister(ctx context.Context, in *Registration, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/registry.Registry/Unregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) FetchServiceLocation(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RegistrationList, error) {
	out := new(RegistrationList)
	err := c.cc.Invoke(ctx, "/registry.Registry/fetchServiceLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	Register(context.Context, *Registration) (*RegisterResponse, error)
	Unregister(context.Context, *Registration) (*RegisterResponse, error)
	FetchServiceLocation(context.Context, *empty.Empty) (*RegistrationList, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Registration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).Register(ctx, req.(*Registration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Registration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).Unregister(ctx, req.(*Registration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_FetchServiceLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).FetchServiceLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/FetchServiceLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).FetchServiceLocation(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "registry.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Registry_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _Registry_Unregister_Handler,
		},
		{
			MethodName: "fetchServiceLocation",
			Handler:    _Registry_FetchServiceLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
